// This file was autogenerated by /usr/share/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('module/itrustmoduleloader.js', ['itrust.module.ModuleLoader'], ['goog.module.ModuleLoader']);
goog.addDependency('module/itrustmodulemanager.js', ['itrust.module.ModuleManager'], ['goog.module.ModuleManager']);
